# Generated by Django 3.1.2 on 2020-10-29 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20201029_1856'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AlterField(
            model_name='poem',
            name='description',
            field=models.CharField(default=None, max_length=500),
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(default=None, max_length=500)),
                ('score', models.IntegerField(default=0)),
                ('poem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.poem')),
            ],
        ),
        migrations.AlterField(
            model_name='poem',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
    ]
