# Generated by Django 3.1.2 on 2020-10-29 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201029_1909'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poem',
            name='description',
        ),
        migrations.CreateModel(
            name='PoemLines',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line', models.CharField(default=None, max_length=500)),
                ('poem_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.poem')),
            ],
        ),
    ]
