# Generated by Django 3.1.2 on 2020-10-29 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20201029_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poemlines',
            name='line',
            field=models.TextField(default=None),
        ),
    ]
