# Generated by Django 3.1.2 on 2020-10-29 20:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20201029_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
