# Generated by Django 3.1.2 on 2020-10-29 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_suggestion_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='description',
            field=models.TextField(default=None),
        ),
        migrations.DeleteModel(
            name='PoemLines',
        ),
    ]
