# Generated by Django 3.1.2 on 2020-10-29 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20201029_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
    ]
