# Generated by Django 3.1.2 on 2020-10-29 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20201029_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='description',
            field=models.TextField(default=None),
        ),
    ]
